/**
 * Draft-related views
 */

import type { Env, ViewResult, Draft, DraftContent, InlineButton, PublishResults } from '../types';
import { getAllDrafts, countDrafts, getDraft, getPublishedByDraft, getHandwriteDraftCount, getDraftsBySource, countDraftsBySource } from '../data/db';
import { getUser } from '../data/user-db';
import { formatLocalTime } from '../infra/timezone';
import { escapeHtml, truncateHtml } from '../ui/utils';
import { homeButton, backButton, backHomeRow, paginationRows, cancelRow } from '../ui/components';
import { t } from '../ui/strings';
import type { Lang } from '../ui/strings';
import { renderPlatformBadges, parsePublishTargets, renderPublishResults, platformEmoji } from './platform-toggle';

export type DraftListType = 'auto' | 'approved' | 'scheduled' | 'handwrite' | 'published' | 'repost';

// Short codes for callback_data (Telegram 64-byte limit)
const listTypeToShort: Record<string, string> = { auto: 'a', handwrite: 'h', approved: 'v', scheduled: 's', published: 'p', repost: 'r' };
export const shortToListType: Record<string, DraftListType> = { a: 'auto', h: 'handwrite', v: 'approved', s: 'scheduled', p: 'published', r: 'repost' };

const statusEmoji: Record<string, string> = {
    draft: '📝',
    approved: '✅',
    scheduled: '📅',
    published: '📤',
};

export async function renderDraftCategories(env: Env, chatId: string, lang: Lang = 'en'): Promise<ViewResult> {
    const [autoCount, handwriteCount, repostCount, approvedCount, scheduledCount, publishedCount] = await Promise.all([
        countDraftsBySource(env, chatId, ['auto', 'commit'], ['draft']),
        getHandwriteDraftCount(env, chatId),
        countDraftsBySource(env, chatId, 'repost', ['draft']),
        countDrafts(env, chatId, 'approved'),
        countDrafts(env, chatId, 'scheduled'),
        countDrafts(env, chatId, 'published'),
    ]);

    const total = autoCount + handwriteCount + repostCount + approvedCount + scheduledCount + publishedCount;

    if (total === 0) {
        return {
            text: `${t(lang, 'drafts.title')}

${t(lang, 'drafts.noDrafts')}`,
            keyboard: [
                [{ text: t(lang, 'home.btnGenerate'), callback_data: 'view:generate', style: 'primary' }],
                [{ text: t(lang, 'home.btnHandwrite'), callback_data: 'view:handwrite' }],
                [homeButton(lang)],
            ],
        };
    }

    return {
        text: `${t(lang, 'drafts.title')} (${total} ${t(lang, 'common.total')})

${t(lang, 'drafts.selectCategory')}`,
        keyboard: [
            [{ text: `${t(lang, 'drafts.autoGenerated')} (${autoCount})`, callback_data: 'view:drafts_auto' }],
            [{ text: `${t(lang, 'drafts.handwritten')} (${handwriteCount})`, callback_data: 'view:drafts_handwrite' }],
            [{ text: `${t(lang, 'drafts.reposts')} (${repostCount})`, callback_data: 'view:drafts_repost' }],
            [{ text: `${t(lang, 'drafts.approvedLabel')} (${approvedCount})`, callback_data: 'view:drafts_approved', style: 'success' }],
            [{ text: `${t(lang, 'drafts.scheduledLabel')} (${scheduledCount})`, callback_data: 'view:drafts_scheduled' }],
            [{ text: `${t(lang, 'drafts.publishedLabel')} (${publishedCount})`, callback_data: 'view:drafts_published' }],
            [homeButton(lang)],
        ],
    };
}

async function countDraftsForType(env: Env, chatId: string, type: DraftListType): Promise<number> {
    if (type === 'auto') {
        return countDraftsBySource(env, chatId, ['auto', 'commit'], ['draft']);
    }
    if (type === 'approved') return countDrafts(env, chatId, 'approved');
    if (type === 'scheduled') return countDrafts(env, chatId, 'scheduled');
    return 0;
}

export async function renderDraftsList(env: Env, chatId: string, page = 0, listType: DraftListType = 'auto', pageSize = 5, lang: Lang = 'en'): Promise<ViewResult> {
    const limit = pageSize;
    const offset = page * limit;

    let drafts: Draft[];
    let total: number;

    if (listType === 'auto') {
        [drafts, total] = await Promise.all([
            getDraftsBySource(env, chatId, ['auto', 'commit'], ['draft'], limit, offset),
            countDraftsBySource(env, chatId, ['auto', 'commit'], ['draft']),
        ]);
    } else if (listType === 'approved') {
        drafts = await getAllDrafts(env, chatId, 'approved', limit, offset);
        total = await countDrafts(env, chatId, 'approved');
    } else if (listType === 'handwrite') {
        drafts = await getDraftsBySource(env, chatId, 'handwrite', ['draft'], limit, offset);
        total = await countDraftsBySource(env, chatId, 'handwrite', ['draft']);
    } else if (listType === 'repost') {
        drafts = await getDraftsBySource(env, chatId, 'repost', ['draft'], limit, offset);
        total = await countDraftsBySource(env, chatId, 'repost', ['draft']);
    } else if (listType === 'published') {
        drafts = await getAllDrafts(env, chatId, 'published', limit, offset);
        total = await countDrafts(env, chatId, 'published');
    } else {
        drafts = await getAllDrafts(env, chatId, 'scheduled', limit, offset);
        total = await countDrafts(env, chatId, 'scheduled');
    }

    const totalPages = Math.ceil(total / limit);
    const typeLabels: Record<string, string> = { auto: t(lang, 'drafts.typeAuto'), approved: t(lang, 'drafts.typeApproved'), handwrite: t(lang, 'drafts.typeHandwrite'), scheduled: t(lang, 'drafts.typeScheduled'), published: t(lang, 'drafts.typePublished'), repost: t(lang, 'drafts.typeRepost') };
    const typeLabel = typeLabels[listType] || listType;

    if (drafts.length === 0) {
        return {
            text: `📝 <b>${typeLabel} Drafts</b>

${t(lang, 'drafts.noDraftsInType').replace('{type}', typeLabel.toLowerCase())}`,
            keyboard: [
                backHomeRow('view:drafts', lang),
            ],
        };
    }

    // Build display title for each draft
    function getDraftDisplayTitle(d: typeof drafts[0]): string {
        if (d.source === 'auto' && d.pr_title.includes(' | ')) {
            // New format: "repoName | originalTitle" — show repo + first tweet text
            const repo = d.pr_title.split(' | ')[0].substring(0, 10);
            try {
                const content = JSON.parse(d.content) as DraftContent;
                const tweet = content.tweets[0]?.text || '';
                const preview = tweet.length > 30 ? tweet.substring(0, 27) + '...' : tweet;
                return `${repo} — ${preview}`;
            } catch {
                return d.pr_title.split(' | ').slice(1).join(' | ').substring(0, 40);
            }
        }
        if (d.source === 'repost') {
            // Format: "@username | preview..."
            return d.pr_title.length > 40 ? d.pr_title.substring(0, 37) + '...' : d.pr_title;
        }
        if (d.source === 'handwrite') {
            try {
                const content = JSON.parse(d.content) as DraftContent;
                const tweet = content.tweets[0]?.text || d.pr_title;
                return tweet.length > 40 ? tweet.substring(0, 37) + '...' : tweet;
            } catch {
                return d.pr_title.length > 40 ? d.pr_title.substring(0, 37) + '...' : d.pr_title;
            }
        }
        return d.pr_title.length > 40 ? d.pr_title.substring(0, 37) + '...' : d.pr_title;
    }

    const draftLines = drafts.map((d) => {
        const emoji = statusEmoji[d.status] || '📄';
        return `${emoji} <b>${escapeHtml(getDraftDisplayTitle(d))}</b>`;
    });

    // Pre-fetch tweet URLs for published drafts
    const tweetUrls = new Map<string, string>();
    if (listType === 'published') {
        const pubs = await Promise.all(drafts.map(d => getPublishedByDraft(env, chatId, d.id)));
        for (let i = 0; i < drafts.length; i++) {
            if (pubs[i]?.tweet_url) tweetUrls.set(drafts[i].id, pubs[i]!.tweet_url!);
        }
    }

    // Two rows per draft: title row + quick action row
    const draftButtons: InlineButton[][] = [];
    for (const d of drafts) {
        const emoji = statusEmoji[d.status] || '📄';
        const title = getDraftDisplayTitle(d);
        // Append platform badges if draft targets Instagram platforms
        const dTargets = parsePublishTargets(d.publish_targets);
        const igBadges = [
            dTargets.instagram_post ? platformEmoji('instagram_post') : '',
            dTargets.instagram_story ? platformEmoji('instagram_story') : '',
            dTargets.instagram_reel ? platformEmoji('instagram_reel') : '',
        ].filter(Boolean).join('');
        const badgeSuffix = igBadges ? ` ${igBadges}` : '';
        // Row 1: title button (navigates to draft detail)
        draftButtons.push([{ text: `${emoji} ${title}${badgeSuffix}`, callback_data: `draft:${d.id}` }]);
        // Row 2: quick action buttons based on status
        // Use abbreviated names to stay under Telegram's 64-byte callback_data limit
        const lt = listTypeToShort[listType] || listType;
        const ctx = `${d.id}:${lt}:${page}`;
        const actions: InlineButton[] = [];
        if (d.status === 'draft') {
            actions.push({ text: '✅', callback_data: `action:la:${ctx}`, style: 'success' });
        }
        if (d.status === 'approved') {
            actions.push({ text: '📤', callback_data: `action:lp:${ctx}`, style: 'success' });
        }
        if (d.status === 'scheduled') {
            actions.push({ text: '📤', callback_data: `action:lp:${ctx}`, style: 'success' });
        }
        if (d.status === 'published') {
            const url = tweetUrls.get(d.id);
            if (url) actions.push({ text: '🔗', url, style: 'primary' });
        }
        // Schedule button for all except scheduled and published
        if (d.status !== 'scheduled' && d.status !== 'published') {
            actions.push({ text: '📅', callback_data: `action:schedule:${d.id}`, style: 'primary' });
        }
        actions.push({ text: '🗑', callback_data: `action:ld:${ctx}`, style: 'danger' });
        draftButtons.push(actions);
    }

    return {
        text: `📝 <b>${typeLabel} Drafts</b> (${total} ${t(lang, 'common.total')})

${draftLines.join('\n')}

${t(lang, 'common.page')} ${page + 1} ${t(lang, 'common.of')} ${totalPages}`,
        keyboard: [
            ...draftButtons,
            ...paginationRows(listType, page, page < totalPages - 1, lang),
            backHomeRow('view:drafts', lang),
        ],
    };
}

export async function renderDraftDetail(env: Env, chatId: string, draftId: string, timezone = 'UTC', lang: Lang = 'en', showPlatformToggles = false): Promise<ViewResult> {
    const draft = await getDraft(env, draftId, chatId);

    if (!draft) {
        return {
            text: `${t(lang, 'drafts.notFoundTitle')}

${t(lang, 'drafts.notFoundMsg')}`,
            keyboard: [[backButton('view:drafts', lang)]],
        };
    }

    const content = JSON.parse(draft.content) as DraftContent;

    const tweetPreview = content.tweets
        .map((tw, i) => {
            const mediaIndicator = tw.media?.length ? ' 📷' : '';
            return `<b>${t(lang, 'drafts.tweetN').replace('{n}', String(i + 1))}</b>${mediaIndicator} ${escapeHtml(tw.text)}`;
        })
        .join('\n\n');

    // Parse publish targets for badges
    const targets = parsePublishTargets(draft.publish_targets);
    const platformBadges = renderPlatformBadges(targets);

    let statusLine = `${statusEmoji[draft.status]} <code>${draft.status.toUpperCase()}</code>`;
    if (draft.status === 'scheduled' && draft.scheduled_at) {
        statusLine += ` for <code>${formatLocalTime(draft.scheduled_at, timezone)}</code>`;
    }

    // Add platform badges to status line
    if (platformBadges) {
        statusLine += `\n${t(lang, 'platforms.targets')}: ${platformBadges}`;
    }

    const user = await getUser(env, chatId);
    const hasInstagram = user?.has_instagram === 1;

    // Build platform toggle rows (inline) or single platform button
    const hasVideo = draft.has_video === 1;
    const check = (enabled: boolean) => enabled ? '✅' : '⬜';

    function platformToggleRows(): InlineButton[][] {
        const rows: InlineButton[][] = [];
        rows.push([{
            text: `${check(targets.x)} 🐦 ${t(lang, 'platforms.x')}`,
            callback_data: `plat:toggle:x:${draftId}`,
        }]);
        if (hasInstagram) {
            rows.push([{
                text: `${check(targets.instagram_post)} 📸 ${t(lang, 'platforms.post')}`,
                callback_data: `plat:toggle:instagram_post:${draftId}`,
            }]);
            rows.push([{
                text: `${check(targets.instagram_story)} 📖 ${t(lang, 'platforms.story')}`,
                callback_data: `plat:toggle:instagram_story:${draftId}`,
            }]);
            if (hasVideo) {
                rows.push([{
                    text: `${check(targets.instagram_reel)} 🎬 ${t(lang, 'platforms.reel')}`,
                    callback_data: `plat:toggle:instagram_reel:${draftId}`,
                }]);
            }
        }
        return rows;
    }

    function platformButtonRow(): InlineButton[][] {
        return [[{ text: `🎯 ${t(lang, 'platforms.btnPlatforms')}`, callback_data: `plat:show:${draftId}` }]];
    }

    let actionButtons: InlineButton[][] = [];

    // When platform toggles are open, they replace the action buttons entirely
    if (showPlatformToggles && draft.status !== 'published') {
        actionButtons = platformToggleRows();
    } else switch (draft.status) {
        case 'draft':
            actionButtons = [
                [
                    { text: t(lang, 'drafts.approve'), callback_data: `action:approve:${draft.id}`, style: 'success' },
                    { text: t(lang, 'common.delete'), callback_data: `action:delete_draft:${draft.id}`, style: 'danger' },
                ],
                [
                    { text: draft.source === 'handwrite' ? t(lang, 'drafts.aiRefine') : t(lang, 'drafts.edit'), callback_data: `action:edit:${draft.id}`, style: 'primary' as const },
                    { text: t(lang, 'drafts.schedule'), callback_data: `action:schedule:${draft.id}`, style: 'primary' as const },
                ],
                ...platformButtonRow(),
            ];
            break;
        case 'approved':
            actionButtons = [
                [
                    { text: t(lang, 'drafts.publishNow'), callback_data: `action:publish:${draft.id}`, style: 'success' as const },
                    { text: t(lang, 'drafts.schedule'), callback_data: `action:schedule:${draft.id}`, style: 'primary' as const },
                ],
                ...platformButtonRow(),
            ];
            break;
        case 'scheduled':
            actionButtons = [
                [
                    { text: t(lang, 'drafts.publishNow'), callback_data: `action:publish:${draft.id}`, style: 'success' as const },
                    { text: t(lang, 'common.cancel'), callback_data: `action:unschedule:${draft.id}`, style: 'danger' },
                ],
                ...platformButtonRow(),
            ];
            break;
        case 'published': {
            // Show per-platform results
            let publishResults: PublishResults = {};
            try {
                publishResults = draft.publish_results ? JSON.parse(draft.publish_results) : {};
            } catch { /* ignore */ }

            const resultLine = renderPublishResults(publishResults, publishResults.errors, lang);

            // Build URL buttons for successful platforms
            const urlButtons: InlineButton[] = [];
            if (publishResults.x?.url) {
                urlButtons.push({ text: '🐦 X', url: publishResults.x.url });
            }
            if (publishResults.instagram_post?.url) {
                urlButtons.push({ text: '📸 Post', url: publishResults.instagram_post.url });
            }
            if (publishResults.instagram_reel?.url) {
                urlButtons.push({ text: '🎬 Reel', url: publishResults.instagram_reel.url });
            }

            if (urlButtons.length > 0) {
                actionButtons.push(urlButtons);
            }

            // Repost button — publish to additional platforms
            if (hasInstagram) {
                actionButtons.push([
                    { text: `🔄 ${t(lang, 'platforms.btnRepost')}`, callback_data: `plat:repost:show:${draft.id}` },
                ]);
            }

            // Add result line to status
            if (resultLine) {
                statusLine += `\n${resultLine}`;
            }

            // Fallback: show published record URL if no per-platform results
            if (!publishResults.x && !publishResults.instagram_post) {
                const published = await getPublishedByDraft(env, chatId, draft.id);
                if (published) {
                    // No URL to show from simplified published record
                }
            }
            break;
        }
    }

    let headerLabel: string;
    if (draft.source === 'repost') {
        headerLabel = t(lang, 'drafts.repostDraft');
    } else if (draft.source === 'handwrite') {
        headerLabel = t(lang, 'drafts.handwrittenDraft');
    } else {
        headerLabel = t(lang, 'drafts.draftForPr').replace('{number}', String(draft.pr_number));
    }

    const originalLink = draft.original_tweet_url
        ? `\n🔗 <a href="${draft.original_tweet_url}">${t(lang, 'drafts.originalTweet')}</a>`
        : '';

    return {
        text: `${headerLabel}

<b>${escapeHtml(draft.pr_title)}</b>${originalLink}

${statusLine}
${t(lang, 'drafts.format')} ${t(lang, 'common.arrow')} <code>${content.format === 'single' ? t(lang, 'drafts.singleTweet') : `Thread (${content.tweets.length} tweets)`}</code>

${tweetPreview}`,
        keyboard: [
            ...actionButtons,
            [backButton(showPlatformToggles ? `plat:done:${draftId}` : 'view:drafts', lang)],
        ],
    };
}

export function renderGeneratePrompt(lang: Lang = 'en'): ViewResult {
    return {
        text: `${t(lang, 'drafts.generateTitle')}

${t(lang, 'drafts.generateDesc')}`,
        keyboard: [cancelRow('view:home', lang)],
    };
}

export function renderSchedulePrompt(lang: Lang = 'en'): ViewResult {
    return {
        text: `${t(lang, 'drafts.scheduleTitle')}

${t(lang, 'drafts.scheduleDesc')}`,
        keyboard: [cancelRow('view:home', lang)],
    };
}

export function renderDeleteDraftConfirm(draftId: string, title: string, lang: Lang = 'en'): ViewResult {
    const safeTitle = escapeHtml(title.length > 60 ? title.substring(0, 57) + '...' : title);
    const text = `${t(lang, 'drafts.deleteDraftTitle')}

<b>${safeTitle}</b>

${t(lang, 'drafts.deleteDraftWarn')}`;

    // Keep under 1024 chars for photo caption compatibility
    const caption = truncateHtml(text, 1024);

    return {
        text: caption,
        keyboard: [
            [
                { text: t(lang, 'common.yesDelete'), callback_data: `action:confirm_delete:${draftId}`, style: 'danger' },
                { text: t(lang, 'common.cancel'), callback_data: `action:cancel_delete:${draftId}`, style: 'danger' },
            ],
        ],
    };
}

export function renderDeletePrompt(lang: Lang = 'en'): ViewResult {
    return {
        text: `${t(lang, 'drafts.deleteTitle')}

${t(lang, 'drafts.deleteDesc')}`,
        keyboard: [cancelRow('view:home', lang)],
    };
}
