/**
 * Hebrew string registry — all user-facing strings
 * Structure mirrors en.ts exactly. Maintainer fills in native Hebrew.
 * Missing keys fall back to English via the t() function.
 */

import type { StringsMap } from './en';

export const he: StringsMap = {
    common: {
        home: '🏠 בית',
        back: '◀️ חזרה',
        cancel: '❌ ביטול',
        on: 'פעיל',
        off: 'כבוי',
        yes: 'כן',
        no: 'לא',
        error: '❌ <b>שגיאה</b>',
        success: '✅ <b>הצלחה!</b>',
        delete: 'מחיקה',
        yesDelete: 'כן, מחק',
        prev: '⬅️ הקודם',
        next: 'הבא ➡️',
        example: '<b>דוגמה:</b>',
        loading: 'טוען...',
        tapToChange: 'לחץ על הגדרה כדי לשנות:',
        arrow: '←',
        total: 'סה"כ',
        page: 'עמוד',
        of: 'מתוך',
        done: 'סיום',
    },

    home: {
        title: '🤖 <b>לוח בקרה</b>',
        nextUp: '📅 <b>הבא בתור:</b>',
        queueLabel: '📊 <b>תור:</b>',
        scheduled: 'מתוזמנים',
        drafts: 'טיוטות',
        approved: 'מאושרים',
        allClear: '👋 הכל נקי! אין פוסטים בתור.',
        singleTweet: 'ציוץ בודד',
        pending: 'ממתין',

        btnSchedule: '📅 תזמון',
        btnDrafts: '📝 טיוטות',
        btnHandwrite: '✍️ כתיבה',
        btnGenerate: '⚡ יצירה',
        btnRepost: '🔄 ריפוסט',
        btnRepos: '📦 ריפוז',
        btnAccounts: '👤 חשבונות',
        btnThumbs: '🖼 תמונות ממוזערות',
        btnVideoStudio: '🎬 סטודיו וידאו',
        btnOpenApp: 'פתח אפליקציה',
        btnSettings: '⚙️ הגדרות',
        btnImageCreate: '🎨 תמונה',
        btnHelp: '❓ עזרה',
    },

    help: {
        title: '❓ <b>עזרה</b>',
        createContent: '<b>יצירת תוכן</b>',
        generateDesc: '⚡ <b>יצירה</b> — AI יוצר פוסט מכל קומיט או PR',
        handwriteDesc: '✍️ <b>כתיבה</b> — כתוב ציוץ או שרשור בעצמך',
        repostDesc: '🔄 <b>ריפוסט</b> — ציטוט מכל ציוץ',
        manage: '<b>ניהול</b>',
        draftsDesc: '📝 <b>טיוטות</b> — סקירה, עריכה, אישור, תזמון או מחיקה',
        reposDesc: '📦 <b>ריפוז</b> — מעקב אחרי ריפוז ליצירת תוכן אוטומטית',
        accountsDesc: '👤 <b>חשבונות</b> — מעקב אחרי חשבונות X להצעות ריפוסט',
        howItWorks: '<b>איך זה עובד</b>',
        howItWorksDesc: 'עקוב אחרי ריפו → PRים חדשים יוצרים טיוטות אוטומטית → סקור ופרסם ב-X. פוסטים מתוזמנים יוצאים אוטומטית. תמונות AI נוצרות ומצורפות בפרסום.',
        quickCommands: '<b>פקודות מהירות</b>',
        quickCommandsList: '/generate, /handwrite, /repost, /drafts, /repos, /watch, /help',
    },

    error: {
        tapHome: 'לחץ על בית כדי לחזור ללוח הבקרה.',
        occurred: 'אירעה שגיאה.',
        repoNotFound: 'ריפו לא נמצא.',
        accountNotFound: 'חשבון לא נמצא.',
        draftNotFound: 'טיוטה לא נמצאה.',
        videoNotFound: 'וידאו לא נמצא.',
        invalidTimezone: 'פורמט אזור זמן לא תקין. השתמש בפורמט UTC+N או UTC-N.',
        missingRepo: 'ריפו חסר.',
        missingField: 'שדה חסר.',
        noOverview: 'לא נמצא סקירה. בצע Bootstrap קודם.',
        videoAdminOnly: '❌ סטודיו וידאו זמין רק למנהל.',
        commitEventNotFound: 'אירוע קומיט לא נמצא.',
        commitAlreadyGenerated: 'כבר נוצרה טיוטה לאירוע זה.',
        commitFetchFailed: '❌ <b>קומיט לא נמצא</b>\n\nלא נמצא <code>{sha}</code> בריפוים שלך. וודא שהקומיט נדחף ל-GitHub.\n\nשלח SHA או מספר PR אחר כדי לנסות שוב.',
        githubTokenMissing: '❌ <b>GitHub לא מחובר</b>\n\nצריך להוסיף את הטוקן של GitHub קודם. לך להגדרות ← מפתחות API כדי להגדיר.',
        commitSourceParseFailed: 'נכשל בפענוח נתוני מקור האירוע.',
    },

    success: {
        title: '✅ <b>הצלחה!</b>',
    },

    generating: {
        title: '🔄 <b>מייצר...</b>',
        findingPr: 'מחפש PR לקומיט',
        mayTakeMoment: 'זה עשוי לקחת רגע.',
    },

    publishing: {
        title: '📤 <b>מפרסם...</b>',
        publishingTo: 'מפרסם ב-X...',
        pleaseWait: 'אנא המתן.',
    },

    compose: {
        title: '✍️ <b>כתיבת פוסט</b>',
        instructions: 'שלח לי תוכן — כל הודעה הופכת לציוץ בשרשור.',
        textHint: '📝 <b>טקסט</b> — פשוט כתוב ושלח',
        photoHint: '📷 <b>תמונה</b> — צרף תמונה (עם כיתוב אופציונלי)',
        editHint: '✏️ <b>עריכה</b> — ערוך כל הודעה שנשלחה כדי לעדכן',
        whenDone: 'כשסיימת, לחץ על <b>הנח עט</b> כדי לשמור טיוטה.',
        imageHint: '🎨 <b>תמונה</b> — AI יוצר תמונה מושכת לפוסט שלך',
        aiHint: '✨ <b>שיפור AI</b> — מלטש את הכתיבה שלך תוך שמירה על הקול שלך',
        instructHint: '📝 <b>הוראה</b> — תן ל-AI הוראות מותאמות לתוכן שלך',
        analyzeHint: '📷 <b>ניתוח</b> — AI רואה את התמונות שצירפת לשיפור חכם יותר',
        composing: '✍️ <b>כותב</b>',
        btnPenDown: '✏️ הנח עט',
        btnImage: '🎨 תמונה',
        btnAi: '✨ AI',
        xImageLimit: '⚠️ 𝕏: {count}/4 — רק 4 הראשונות יפורסמו',
        igImageLimit: '⚠️ IG: <s>{count}/10</s> — רק 10 הראשונות יפורסמו',

        // Compose buttons
        btnInstruct: '📝 הוראה',
        btnAnalyze: '📷 ניתוח',
        btnThread: '🧵 שרשור',
        btnLangHe: 'עברית',
        btnLangEn: 'English',

        // Instruction UX
        instructToast: 'הקלד את ההוראה שלך עכשיו',
        awaitingInstruction: '📝 הקלד את ההוראה שלך עכשיו...',
        instructionPrefix: '📝',

        // Repost compose mode
        repostHeader: '🔄 <b>ריפוסט מ-@{username}</b>',
        repostInstructions: 'הוסף ציוצים, תמונות או הוראות משלך — או פשוט לחץ <b>הנח עט</b> ליצירה.',
        repostThreadIndicator: '🧵 שרשור',
        repostImageIndicator: '🖼 יש תמונה',
        andMoreTweets: '...ועוד {count}',

        // Commit compose mode
        commitHeader: '📌 <b>{repoShort} | {title}</b>',
        commitStats: '{commits} קומיטים · {files} קבצים',
        commitStatsFull: '{commits} קומיטים · {files} קבצים · +{additions} / -{deletions}',
        commitInstructions: 'הוסף ציוצים משלך, צרף תמונות, או לחץ <b>הנח עט</b> ליצירה מהשינוי הזה.',

        // Compose status messages
        generatingFromInstruction: '✨ מייצר מהוראה...',
        refiningAndImage: '✨ משפר טקסט ומייצר תמונה...',
        refiningAi: '✨ משפר עם AI...',
        generatingImagePrompt: '🖼 מייצר הוראות תמונה...',
        savingDraft: '💾 שומר טיוטה...',
        generatingImage: '🎨 מייצר תמונה...',
    },

    settings: {
        title: '⚙️ <b>הגדרות</b>',
        timezone: '🕐 <b>אזור זמן:</b>',
        pageSize: '📏 <b>גודל עמוד:</b>',
        language: '🌐 <b>שפה:</b>',
        items: 'פריטים',
        utcDefault: 'UTC (ברירת מחדל)',

        btnTimezone: '🕐 אזור זמן',
        btnPageSize: '📏 גודל עמוד',
        btnApiKeys: '🔑 מפתחות API',
        btnSystemPrompts: 'פרומפטים של המערכת',
        btnSystemPromptsAdmin: 'פרומפטים של המערכת (מנהל)',
        btnLanguage: '🌐',
        btnAnalyzeIdentity: '🪞 ניתוח זהות',

        // Identity language notification
        identityLangNotification: '🪞 <b>הזהות לא זמינה בשפה זו</b>\n\nהזהות שלך נותחה בשפה אחרת. ניתן לנתח מחדש בשפה הנוכחית, או להשתמש בזהות ברירת המחדל.',
        btnReanalyzeIdentity: '🪞 ניתוח מחדש',
        btnKeepDefault: '👍 השאר ברירת מחדל',
        identityNoX: '⚠️ נדרשים פרטי X/Twitter לניתוח זהות.',
        identityNoXConnect: '⚠️ נדרשים פרטי X/Twitter לניתוח זהות.\n\nיש לחבר את חשבון ה-X שלך תחילה מהגדרות מפתחות API.',
        identityReanalyzed: '✅ <b>ניתוח הזהות הושלם!</b>\n\nמסמך הזהות שלך עודכן.',
        identityReanalyzedWebApp: '✅ <b>ניתוח הזהות הושלם!</b>\n\nמסמך הזהות שלך עודכן. ניתן לצפות ולערוך אותו באפליקציית הווב.',
        identityAnalyzeFailed: '⚠️ הניתוח נכשל. הזהות הקיימת שלך נשארת ללא שינוי.',
        identityAnalyzeFailedRetry: '⚠️ הניתוח נכשל. נסה שוב מאוחר יותר.\n\nהזהות הקיימת שלך נשארת ללא שינוי.',
        identityAnalyzeFailedNoTweets: '⚠️ הניתוח נכשל. לא נמצאו ציוצים או שאירעה שגיאה.\n\nהזהות הקיימת שלך נשארת ללא שינוי.',
        identityReconnectX: '⚠️ החיבור ל-X פג. חבר מחדש את חשבון ה-X שלך באפליקציית הווב, ואז נסה שוב לנתח זהות.\n\nהזהות הקיימת שלך נשארת ללא שינוי.',

        // Repost defaults
        repostDefaults: '🔄 <b>ברירות מחדל ריפוסט</b>',
        btnFastImage: '🎨 תמונה מהירה',
        btnSourceAnalysis: '📷 ניתוח מקור',

        // Commit defaults
        commitDefaults: '💻 <b>ברירות מחדל קומיטים</b>',
        btnCommitFastImage: '🎨 תמונה אוטומטית',
        btnCommitFastAi: '🤖 AI אוטומטי',

        // Repo defaults
        repoDefaults: '📦 <b>ברירות מחדל ריפו</b>',
        btnAutoOverview: '🔍 סקירה אוטומטית',
        btnWatchPushes: '📤 מעקב פושים',

        languageEn: '🇺🇸 English',
        languageHe: '🇮🇱 עברית',

        // Category buttons
        btnCatGeneral: '⚙️ כללי',
        btnCatSkills: '🧠 כישורים',
        btnCatPlatforms: '📱 פלטפורמות',
        btnCatRepost: '🔄 ריפוסט',
        btnCatCommits: '📝 קומיטים',
        btnCatRepos: '📦 ריפו',

        // Sub-page titles
        subGeneralTitle: '⚙️ <b>הגדרות כלליות</b>',
        subSkillsTitle: '🧠 <b>כישורים וזהות</b>',
        subPlatformsTitle: '📱 <b>פלטפורמות</b>',
        subRepostTitle: '🔄 <b>הגדרות ריפוסט</b>',
        subCommitsTitle: '📝 <b>הגדרות קומיטים</b>',
        subReposTitle: '📦 <b>ברירות מחדל ריפו</b>',

        // Sub-page descriptions
        descTimezone: 'שולט בזמני פרסום מתוזמנים ותצוגת זמן.',
        descLanguage: 'שולט בשפת ממשק הבוט.',
        descPageSize: 'מספר פריטים בכל עמוד ברשימות.',
        descSystemPrompts: 'התאם אישית סגנון וטון כתיבת AI.',
        descAnalyzeIdentity: 'סרוק מחדש את פרופיל X שלך לעדכון פרסונת AI.',
        descDefaultPlatforms: 'לאילו פלטפורמות טיוטות חדשות מכוונות כברירת מחדל.',
        descApiKeys: 'ניהול פרטי התחברות לשירותים.',
        descFastImage: 'יצירת תמונת AI בעת יצירת טיוטות ריפוסט דרך יצירה מהירה.',
        descSourceAnalysis: 'שליחת תמונת הציוץ המקורי ל-AI כהקשר בעת יצירת ריפוסט.',
        descCommitFastImage: 'יצירת תמונת AI בעת יצירת טיוטות מקומיטים של GitHub.',
        descCommitFastAi: 'שכלול אוטומטי של תוכן קומיט עם AI לפני יצירת הטיוטה.',
        descAutoOverview: 'יצירת סקירת פרויקט אוטומטית בעת הוספת ריפו חדש.',
        descWatchPushes: 'מעקב אחר אירועי פוש כברירת מחדל בריפו חדשים.',
        subReposNote: 'הגדרות אלה חלות על ריפו שנוספים מעכשיו בלבד.',

        timezoneTitle: '🕐 <b>בחר אזור זמן</b>',
        timezoneDesc: 'בחר היסט UTC או הקלד מותאם אישית:',
        timezoneCustom: '⌨️ הקלד היסט מותאם',
        timezoneInputTitle: '⌨️ <b>אזור זמן מותאם</b>',
        timezoneInputDesc: 'הקלד את היסט ה-UTC שלך:',
        timezoneInputExamples: 'דוגמאות: <code>UTC+2</code>, <code>UTC-5:30</code>, <code>UTC+9:45</code>',

        pageSizeTitle: '📏 <b>גודל עמוד</b>',
        pageSizeDesc: 'בחר כמה פריטים להציג בכל עמוד:',
        pageSizeCurrent: 'נוכחי:',

        // Identity analysis depth
        btnTweetDepth: '🔍 עומק ניתוח',
        tweetDepth: '🔍 עומק ניתוח',
        descTweetDepth: 'כמה פוסטים אחרונים לנתח בעת בניית הזהות שלך.',
        tweetDepthTitle: '🔍 <b>עומק ניתוח זהות</b>',
        tweetDepthDesc: 'בחר כמה מהפוסטים האחרונים שלך Muse קורא כדי לבנות את הזהות שלך. יותר פוסטים = ניתוח עשיר יותר, אך זה לוקח קצת יותר זמן.',
        tweetDepthCurrent: 'נוכחי',

        // AI Provider
        aiProvider: 'ספק AI',
        descAiProvider: 'בחר איזה מודל AI יוצר את התוכן שלך.',
        switchToClaude: 'עבור ל-Claude',
        switchToGemini: 'עבור ל-Gemini',
        claudeKeyRequired: '❌ צריך להוסיף מפתח Claude API קודם. עבור למפתחות API למטה כדי לחבר.',

        apiKeysTitle: '🔑 <b>מפתחות API</b>',
        geminiAi: 'Gemini AI',
        claudeAi: 'Claude AI',
        xTwitter: 'X/Twitter',
        github: 'GitHub',
        instagram: 'Instagram',
        linkedin: 'לינקדאין',
        update: 'עדכן',
        connect: 'חבר',
        connected: 'מחובר',
        notConnected: 'לא מחובר',
    },

    repos: {
        title: '📦 <b>ריפוז במעקב</b>',
        noRepos: 'אין ריפוז במעקב עדיין.\n\nהוסף ריפו כדי להתחיל לזהות PRים וקומיטים חדשים!',
        tapToManage: 'לחץ על ריפו לניהול הגדרות.',
        addRepo: '➕ הוסף ריפו',
        watching: '👁 במעקב',
        paused: '⏸️ מושהה',

        watchSettings: '<b>הגדרות מעקב:</b>',
        prs: 'PRים',
        pushes: 'Pushים',
        branches: '📌 ענפים:',

        projectOverview: '<b>סקירת פרויקט:</b>',
        noOverviewYet: 'אין סקירה עדיין — הרץ <code>/overview {repo}</code> ליצירה.',
        noSummary: 'אין תקציר',
        editOverview: '✏️ ערוך סקירה',
        rebootstrap: '🔄 אתחול מחדש',
        bootstrapOverview: '🔍 צור סקירה',

        stopWatching: 'הפסק מעקב',
        startWatching: 'התחל מעקב',

        addRepoTitle: '➕ <b>הוסף ריפו</b>',
        addRepoDesc: 'שלח לי את הריפו בפורמט <code>owner/repo</code>.\n\nאגדיר webhook לזיהוי אוטומטי של PRים וקומיטים חדשים.',
        addRepoExample: 'ozkeisar/work-content-tracker',

        deleteRepoTitle: 'מחק ריפו?',
        deleteRepoMsg: 'האם אתה בטוח שברצונך למחוק:\n<code>{repo}</code>\n\nפעולה זו תסיר גם את ה-webhook מ-GitHub.',

        push: 'Push',

        editOverviewTitle: '✏️ <b>ערוך סקירה</b>',
        editOverviewDesc: 'בחר שדה לעריכה:',
        fieldSummary: '📋 תקציר',
        fieldTechStack: '🛠 מחסנית טכנולוגית',
        fieldKeyFeatures: '⭐ תכונות מרכזיות',
        fieldTargetAudience: '👥 קהל יעד',
        fieldBrandVoice: '🎤 קול מותג',
        fieldVisualTheme: '🎨 ערכת נושא חזותית',
        editFieldTitle: '✏️ <b>ערוך {label}</b>',
        currentValue: '<b>ערך נוכחי:</b>',
        sendNewValue: 'שלח את הערך החדש:',
        empty: '(ריק)',
        summaryLabel: 'תקציר',
        techStackLabel: 'מחסנית טכנולוגית',
        keyFeaturesLabel: 'תכונות מרכזיות (מופרדות בפסיקים)',
        targetAudienceLabel: 'קהל יעד',
        brandVoiceLabel: 'קול מותג',
        visualThemeLabel: 'ערכת נושא חזותית',
    },

    accounts: {
        title: '👤 <b>חשבונות במעקב</b>',
        noAccounts: 'אין חשבונות במעקב עדיין.\n\nהוסף חשבון Twitter/X כדי להתחיל לזהות ציוצים חדשים לריפוסט!',
        tapToManage: 'לחץ על חשבון לניהול הגדרות.',
        addAccount: '➕ הוסף חשבון',

        repostSettings: '<b>הגדרות ריפוסט:</b>',
        threshold: '🎯 סף:',
        autoApprove: 'אישור אוטומטי:',

        personaLabel: '<b>פרסונה:</b>',
        noPersona: 'אין פרסונה עדיין — לחץ על Bootstrap ליצירה.',
        updatePersona: '🔍 עדכן פרסונה',
        bootstrapPersona: '🔍 צור פרסונה',

        unfollow: 'הפסק מעקב',
        follow: 'עקוב',

        addAccountTitle: '➕ <b>הוסף חשבון Twitter</b>',
        addAccountDesc: 'שלח לי את שם המשתמש Twitter/X למעקב.\n\nאתחיל לעקוב אחרי ציוצים חדשים ואודיע לך כשיש משהו שווה ריפוסט.',
        addAccountExample: '@vercel או vercel',

        deleteAccountTitle: 'מחק חשבון?',
        deleteAccountMsg: 'האם אתה בטוח שברצונך להפסיק לעקוב:\n<b>@{username}</b>\n\nפעולה זו תמחק גם את כל הציוצים ונתוני הפרסונה השמורים.',

        auto: 'אוטומטי',
        analyzeMedia: 'ניתוח מדיה',
    },

    drafts: {
        title: '📝 <b>טיוטות</b>',
        noDrafts: 'אין טיוטות עדיין. השתמש ב-⚡ יצירה או ✍️ כתיבה ליצירת אחת!',
        selectCategory: 'בחר קטגוריה:',
        autoGenerated: '📤 נוצרו אוטומטית',
        handwritten: '✍️ כתובות ביד',
        reposts: '🔄 ריפוסטים',
        approvedLabel: 'מאושרות',
        scheduledLabel: '📅 מתוזמנות',
        publishedLabel: '🗂 פורסמו',

        typeAuto: 'נוצרו אוטומטית',
        typeApproved: 'מאושרות',
        typeHandwrite: 'כתובות ביד',
        typeScheduled: 'מתוזמנות',
        typePublished: 'פורסמו',
        typeRepost: 'ריפוסטים',

        noDraftsInType: 'לא נמצאו טיוטות {type}.',

        repostDraft: '🔄 טיוטת ריפוסט',
        handwrittenDraft: '✍️ טיוטה בכתב יד',
        draftForPr: '📋 טיוטה ל-PR #{number}',
        originalTweet: '🔗 ציוץ מקורי',
        format: '<b>פורמט:</b>',
        singleTweet: 'ציוץ בודד',
        tweetN: '<b>ציוץ {n}:</b>',

        approve: '✅ אישור',
        publishNow: '📤 פרסם עכשיו',
        schedule: '📅 תזמן',
        aiRefine: '✨ שיפור AI',
        edit: '✏️ עריכה',
        viewOnX: '🔗 צפה ב-X',

        deleteDraftTitle: '🗑 <b>מחק טיוטה?</b>',
        deleteDraftWarn: '⚠️ פעולה זו תמחק את הטיוטה לצמיתות. לא ניתן לבטל פעולה זו.',

        generateTitle: '⚡ <b>יצירת תוכן</b>',
        generateDesc: 'שלח לי SHA של קומיט.\n\nדוגמה: <code>abc1234</code>\n\nכברירת מחדל אכתוב פוסט על אותו קומיט בלבד. לחץ על כפתור ה-PR למטה כדי להשתמש בכל הקומיטים מה-PR שלו.',
        btnPrModeOff: '🔀 השתמש בכל ה-PR',
        btnPrModeOn: '✅ מצב PR פעיל — כל ה-PR',
        prModeHint: '🔀 <b>מצב PR</b>: ארחיב את הקומיט ל-PR שלו ואשתמש בכל הקומיטים שבו.',

        scheduleTitle: '📅 <b>תזמון פוסט</b>',
        scheduleDesc: 'שלח לי את SHA של הקומיט ותאריך-שעה.\n\nפורמט: <code>abc1234 2024-01-15 14:00</code>\n\nהתוכן ייוצר עכשיו ויפורסם בזמן המתוזמן.',

        deleteTitle: '🗑️ <b>מחק פוסטים</b>',
        deleteDesc: 'שלח לי SHA של קומיט כדי למצוא פוסטים שפורסמו מה-PR.\n\nדוגמה: <code>abc1234</code>\n\nאציג לך את כל הפוסטים כדי שתוכל לבחור מה למחוק.',

        notFoundTitle: '❌ <b>טיוטה לא נמצאה</b>',
        notFoundMsg: 'ייתכן שטיוטה זו נמחקה.',

        retrieving: '⏳ <b>מאחזר את הטיוטה שלך...</b>',
    },

    onboarding: {
        // Welcome (merged value prop)
        welcomeTitle: '🎭 <b>ברוכים הבאים ל-Muse!</b>',
        welcomeSubtitle: 'שותף AI ליצירת תוכן ב-X/Twitter ו-Instagram.',
        welcomeDesc: 'אעזור לך להפוך את הקוד והרעיונות שלך לפוסטים מלוטשים — בקול שלך.',
        welcomeFeatures: '<b>מה אפשר לעשות:</b>',
        welcomeFeatureRepost: '🔄 <b>ריפוסט</b> — הפוך כל ציוץ לפוסט בסגנון שלך',
        welcomeFeatureGenerate: '⚡ <b>יצירה</b> — צור תוכן מקומיטים ב-GitHub',
        welcomeFeatureHandwrite: '✍️ <b>כתיבה</b> — כתוב ציוצים עם שיפור AI',
        welcomeFeatureFollow: '👤 <b>מעקב</b> — עקוב אחרי חשבונות X וצור ריפוסטים אוטומטית',
        welcomeSetup: 'בוא נחבר את החשבונות שלך כדי להתחיל.',
        welcomeDisclaimer: '<i>אתה מביא מפתחות API משלך. כל המפתחות מוצפנים ולעולם לא משותפים.</i>',
        langEn: '🇺🇸 English',
        langHe: '🇮🇱 עברית',
        btnLetsGo: '🚀 יאללה!',

        // X/Twitter (שלב 1 — שחרר את המחשבות שלך)
        xTitle: '🔓 <b>שחרר את המחשבות שלך</b>',
        xDesc: 'X הוא המקום שבו המחשבות שלך חיות. חבר אותו כדי לפתוח:',
        xFeatureRepost: '🔄 הדבק כתובת ציוץ → קבל טיוטת ציטוט בסגנון שלך',
        xFeatureHandwrite: '✍️ כתוב ציוצים ושרשורים עם ליטוש AI שנשמע כמוך',
        xFeatureFollow: '👤 עקוב אחרי חשבונות X וקבל טיוטות ריפוסט אוטומטיות',
        xFeatureIdentity: '🪞 ניתוח הציוצים שלך כדי ללמוד את סגנון הכתיבה הייחודי שלך',
        xConnectViaApp: '🔗 התחבר ל-X באפליקציית הוויב — פתח אותה למטה ולחץ <b>התחבר ל-X</b> (התחברות מאובטחת, בלי להעתיק מפתחות).',
        xFormat: '<b>שלח 4 ערכים</b> (אחד בכל שורה):',
        xKey: '<code>API_KEY</code>',
        xSecret: '<code>API_SECRET</code>',
        xAccessToken: '<code>ACCESS_TOKEN</code>',
        xAccessSecret: '<code>ACCESS_SECRET</code>',
        xDeleteNote: '<i>(אמחק את ההודעה מיד לאחר שמירה)</i>',
        btnHowToGetThem: '📖 הדרכה',
        btnSkipForNow: '⏭ דלג לעת עתה',
        xSuccess: '✅ <b>X/Twitter מחובר!</b>',

        // Instagram (שחרר את ההגעה שלך)
        instagramTitle: '🔓 <b>שחרר את ההגעה שלך</b>',
        instagramDesc: 'התרחב מעבר ל-X — פרסם Reels ופוסטים באינסטגרם.',
        instagramUnlockLabel: 'חבר Instagram כדי לפתוח:',
        instagramFeatureReels: '📱 הפוך את הפוסטים שלך ל-Reels באינסטגרם אוטומטית',
        instagramFeatureCross: '🔀 פרסם גם ב-X וגם באינסטגרם ממקום אחד',
        instagramFormat: '<b>שלח 3 ערכים</b> (אחד בכל שורה):',
        instagramAccessToken: '<code>ACCESS_TOKEN</code>',
        instagramAccountId: '<code>BUSINESS_ACCOUNT_ID</code>',
        instagramAppSecret: '<code>APP_SECRET</code> (Meta App ← App settings ← Basic)',
        instagramDeleteNote: '<i>(אמחק את ההודעה מיד לאחר שמירה)</i>',
        btnInstagramGuide: '📖 Meta Developers',
        instagramSuccess: '✅ <b>Instagram מחובר!</b>',

        // Identity (שחרר את הזהות שלך)
        identityTitle: '🔓 <b>שחרר את הזהות שלך</b>',
        identityDesc: 'זה הרגע הקסום. אנתח את הציוצים האחרונים שלך כדי להבין:',
        identityAspectStyle: '• הקצב וסגנון הכתיבה שלך',
        identityAspectVocab: '• אוצר המילים והטון שלך',
        identityAspectEmotion: '• דפוסי הרגש שלך',
        identityAspectInterests: '• התחומי עניין והפרספקטיבה שלך',
        identityFoundation: 'זה יוצר את מסמך הזהות שלך — הבסיס לכל מה שאכתוב.',
        identityCost: '📊 ~{count} ציוצים מנותחים · קריאת AI אחת',
        identityDepthLabel: 'כמה פוסטים לנתח?',
        identityDepthHint: '⏳ בחירה גדולה יותר לוקחת קצת יותר זמן.',
        btnUnderstandMe: '🔍 תבין אותי',
        btnUseDefault: '📝 השתמש בברירת מחדל',
        identityAnalyzing: '🔍 מנתח את הציוצים שלך... זה עשוי לקחת רגע.',
        identitySuccessTitle: '✅ <b>ניתוח זהות הושלם!</b>',
        identitySnippetLabel: '<b>הנה מה שאני רואה:</b>',
        identitySnippetFooter: '(המסמך המלא זמין בהגדרות)',
        identityFailed: '⚠️ הניתוח לא עבד הפעם. משתמש בזהות ניטרלית — תוכל לנתח מחדש בכל עת מההגדרות.',
        btnNext: 'הבא →',

        // Gemini (שלב 3 — הפעל את ה-AI)
        geminiTitle: '🔓 <b>הפעל את ה-AI</b>',
        geminiDesc: 'עכשיו שאני מכיר את הקול שלך, אני צריך מנוע שיכתוב בו.',
        geminiUnlockLabel: 'חבר Gemini כדי לפתוח:',
        geminiFeatureGeneration: '⚡ AI יוצר פוסטים מקוריים מהקוד והרעיונות שלך',
        geminiFeatureRewriting: '✨ ליטוש כל טיוטה בהתאם לסגנון הכתיבה האישי שלך',
        geminiFeatureIdentity: '🧠 כל טיוטה מעוצבת לפי פרופיל הקול הייחודי שלך',
        geminiGetYours: 'מפתח חינמי · לוקח 30 שניות:',
        geminiLink: 'aistudio.google.com/apikey',
        geminiPaste: '📋 הדבק את המפתח שלך למטה:',
        geminiDeleteNote: '<i>(אמחק את ההודעה שלך מיד לאחר שמירת המפתח)</i>',
        btnHowToGet: '📖 קבל מפתח חינם',
        geminiSuccess: '✅ <b>Gemini מחובר!</b>',

        // GitHub (בונוס — קוד → תוכן)
        githubTitle: '🎁 <b>בונוס: קוד → תוכן</b>',
        githubDesc: 'כותב קוד? תן לי להפוך את הקומיטים שלך לפוסטים.',
        githubUnlockLabel: 'חבר GitHub כדי לפתוח:',
        githubFeatureGenerate: '📝 קומיטים ו-PRים חדשים הופכים לטיוטות מוכנות לפרסום',
        githubFeatureRepos: '👁 מעקב אחרי ריפוז ויצירת תוכן אוטומטית לעדכונים',
        githubCreate: 'צור Personal Access Token ב:',
        githubLink: 'github.com/settings/tokens',
        githubPaste: '📋 הדבק את הטוקן שלך למטה:',
        btnCreateToken: '📖 חבר GitHub',
        btnNotNow: 'לא עכשיו',
        githubSuccess: '✅ <b>GitHub מחובר!</b>',

        // Complete
        completeTitle: '🎉 <b>הכל מוכן!</b>',
        completeUnlockedLabel: '<b>נפתח:</b>',
        completeLockedLabel: '<b>חבר מאוחר יותר כדי לפתוח:</b>',
        featureRepost: '🔄 ריפוסט',
        featureHandwrite: '✍️ כתיבה',
        featureFollow: '👤 מעקב',
        featureIdentity: '🪞 זהות',
        featureInstagram: '📸 פרסום באינסטגרם',
        featureAiGeneration: '🤖 יצירת AI',
        featureCodeToContent: '⚡ קוד → תוכן',
        completeHint: 'נסה /repost עם כתובת ציוץ כלשהי כדי להתחיל!',
        btnAddMoreKeys: '⚙️ הוסף מפתחות נוספים',

        keyErrorTitle: '❌ <b>אימות מפתח {service} נכשל</b>',
        keyErrorDefault: 'נראה שהמפתח אינו תקין. אנא בדוק ונסה שוב.',
        keyErrorRetrySkip: 'הדבק מפתח חדש או דלג על שלב זה.',
        keyErrorRetry: 'הדבק מפתח חדש כדי לנסות שוב.',
    },

    repost: {
        promptTitle: '🔄 <b>ריפוסט ידני</b>',
        promptDesc: 'שלח לי כתובת ציוץ ליצירת ריפוסט.',
        supportedFormats: '<b>פורמטים נתמכים:</b>',
        promptHint: 'אביא את הציוץ, אציג תצוגה מקדימה, ואצור ציוץ ציטוט.',

        previewTitle: '🔄 <b>תצוגה מקדימה של ריפוסט</b>',
        hasImage: '🖼 יש תמונה — תנותח על ידי AI',
        duplicateWarning: '⚠️ <b>כפילות זוהתה</b>\n\nכבר יש לך טיוטת ריפוסט לציוץ זה.',
        viewExisting: '👁 צפה בקיים',
        generateAnyway: '⚡ צור בכל זאת',
        generateRepost: '⚡ צור ריפוסט',
        openTweet: '🔗 פתח ציוץ',

        generatingTitle: '⏳ <b>מייצר ריפוסט ל-@{username}...</b>',
        generatingDesc: 'מביא הקשר ויוצר את ציוץ הציטוט שלך.',
    },

    video: {
        studioTitle: '🎬 <b>סטודיו וידאו</b>',
        studioDesc: 'צור סרטוני אווטאר AI מעדכוני הקוד שלך.',
        studioSelect: 'בחר ריפו או צור סרטון עצמאי:',
        standaloneVideo: '🎬 סרטון עצמאי',
        addRepoFirst: '➕ הוסף ריפו קודם',
        btnVideoSettings: '⚙️ הגדרות וידאו',

        repoSelectCategory: 'בחר קטגוריה או צור סרטון חדש:',
        createNewVideo: '🆕 צור סרטון חדש',

        statusDrafts: '📝 טיוטות',
        statusQueued: '📋 בתור',
        statusGenerating: '⏳ מייצר',
        statusCompleted: '✅ הושלם',
        statusApproved: '👍 מאושר',
        statusScheduled: '📅 מתוזמן',
        statusPublished: '📢 פורסם',
        statusFailed: '❌ נכשל',

        noVideos: 'אין סרטונים בקטגוריה זו.',

        untitled: 'סרטון ללא כותרת',
        status: 'סטטוס:',
        scenes: 'סצנות:',
        words: 'מילים:',
        created: 'נוצר:',
        captionsOn: 'כתוביות: פעיל',
        captionsOff: 'כתוביות: כבוי',
        emotion: 'רגש:',
        preparing: '⏳ מתכונן ליצירה...',
        generatingByHeygen: '⏳ הסרטון נוצר על ידי HeyGen...',
        jobId: 'מזהה עבודה:',
        publishedSuccess: '✅ פורסם בהצלחה.',
        approveGenerate: '✅ אשר וצור',
        regenerateScript: '🔄 צור תסריט מחדש',
        btnDelete: '🗑 מחק',
        btnPublish: '📢 פרסם',
        btnWatch: '▶️ צפה',

        configTitle: '🎬 <b>הגדרות וידאו</b>',
        toneLabel: '🎤  טון:',
        lengthLabel: '⏱  אורך:',
        aspectLabel: '📐  יחס:',
        emotionLabel: '😀  רגש:',
        commitsLabel: '📊  קומיטים:',
        characterLabel: '👤  דמות:',
        notSet: 'לא הוגדר',
        selected: 'נבחר',
        sinceLastVideo: 'מהסרטון האחרון',
        noneStandalone: 'ללא (עצמאי)',
        latestOnly: 'האחרון בלבד',
        captions: 'כתוביות',
        overlay: 'שכבת טקסט',
        textOverlay: 'שכבת טקסט',
        character: 'דמות',
        instructions: 'הוראות',
        savePreset: '💾 שמור תבנית',
        loadPreset: '📂 טען תבנית',
        createVideo: '🎬 צור סרטון',
        tapToCycle: '<i>לחץ על הגדרה כדי לעבור בין אפשרויות</i>',
        instructionsLabel: '📝 <b>הוראות:</b>',

        scriptPreviewTitle: '🎬 <b>תצוגת תסריט: {title}</b>',
        sceneN: '<b>סצנה {n}</b>',
        stats: '📊 <b>נתונים:</b>',
        estimatedCost: '💰 <b>עלות משוערת:</b>',
        premiumCredits: 'קרדיטים פרימיום',
        twitterCaption: '🐦 <b>Twitter:</b>',
        regenerate: '🔄 צור מחדש',
        editConfig: '⚙️ ערוך הגדרות',
        retry: '🔄 נסה שוב',
    },

    videoSettings: {
        title: '🎬 <b>הגדרות וידאו</b>',
        characters: '👤 דמויות:',
        configured: 'מוגדרות',
        voices: '🎙️ קולות: הגדר לכל דמות',
        defaults: '⚙️ ברירות מחדל: מילוי מראש של הגדרות וידאו חדשות',
        btnCharacters: '👤 דמויות',
        btnDefaults: '⚙️ ברירות מחדל',
        btnHeygen: '🔑 חשבון HeyGen',
        btnInstagram: '📸 Instagram',

        charListTitle: '👤 <b>דמויות</b>',
        noChars: 'לא הוגדרו דמויות עדיין.\n\nהוסף דמות כדי להתחיל ליצור סרטונים עם אווטארי תמונה.',
        addCharacter: '➕ הוסף דמות',
        looks: 'מראות',
        look: 'מראה',

        statusReady: 'מוכן',
        statusTraining: 'מאמן...',
        statusFailed: 'נכשל',
        statusLabel: '📊 סטטוס:',
        voiceLabel: '🎙️ קול:',
        emotionLabel: '😊 רגש:',
        personalityLabel: '📝 אישיות:',
        looksTitle: '🎭 <b>מראות',
        looksNone: '🎭 <b>מראות:</b> אין עדיין',
        uploadPhotos: '<i>העלה תמונות כדי להוסיף מראות.</i>',
        btnVoice: '🎙️ קול',
        btnPersonality: '✏️ אישיות',
        checkTraining: '⏳ בדוק אימון...',
        syncLooks: '🔄 סנכרן מראות',
        reTrain: '🧠 אמן מחדש',
        trainAvatar: '🧠 אמן אווטאר',
        addLook: '➕ הוסף מראה',
        removeCharacter: '🗑️ הסר דמות',
        btnCharactersList: '◀️ דמויות',

        removeCharTitle: '⚠️ <b>הסר דמות?</b>',
        removeCharDesc: 'תוסר מההגדרות המקומיות שלך.',
        removeCharNote: 'הערה: קבוצת האווטאר ב-HeyGen לא תימחק. ניתן לנהל אותה בלוח הבקרה של HeyGen.',
        removeCharDrafts: 'טיוטות וידאו קיימות המשתמשות בדמות זו לא יושפעו.',
        yesRemove: '🗑️ כן, הסר',

        voiceSelectTitle: '🎙️ <b>בחר קול ל-{name}</b>',
        currentVoice: 'נוכחי:',
        showing: 'מציג',

        emotionSelectTitle: '😊 <b>רגש ברירת מחדל ל-{name}</b>',
        emotionSelectDesc: 'בחר את הרגש ברירת המחדל לסצנות וידאו:',

        defaultsTitle: '⚙️ <b>הגדרות ברירת מחדל לוידאו</b>',
        defaultsDesc: 'ערכים אלה ממלאים מראש הגדרות וידאו חדשות:',
        aspectRatio: '📐 יחס גובה-רוחב:',
        maxLength: '⏱️ אורך מקסימלי:',
        noLimit: 'ללא הגבלה',
        characterDefault: '👤 דמות:',
        none: 'ללא',
        background: '🎨 רקע:',
        captionsLabel: '📝 כתוביות:',
        btnAspectRatio: '📐 יחס גובה-רוחב',
        btnMaxLength: '⏱️ אורך מקסימלי',
        btnCharacter: '👤 דמות',
        btnBackground: '🎨 רקע',

        heygenTitle: '🔑 <b>חשבון HeyGen</b>',
        apiKey: 'מפתח API:',
        configuredStatus: '✅ מוגדר',
        notConfigured: '❌ לא מוגדר',
        creditCosts: '<b>עלויות קרדיטים:</b>',
        avatarIII: '• Avatar III: קרדיט אחד לדקת וידאו',
        avatarIV: '• Avatar IV: 6 קרדיטים לדקת וידאו',
        photoAvatarTraining: '• אימון Photo Avatar: 4 קרדיטים למראה',

        instagramTitle: '📸 <b>הגדרות Instagram</b>',
        businessAccountId: 'מזהה חשבון עסקי:',
        accessToken: 'טוקן גישה:',
        instagramEnabled: 'פרסום Instagram Reels מופעל.',
        instagramDisabled: 'הגדר את פרטי חשבון Instagram העסקי שלך כדי לאפשר פרסום Reels.',

        removeLook: '🗑️ הסר',
    },

    notifications: {
        newPrMerged: 'PR #{number} מוזג',
        commitsPushed: '{count} קומיט{plural} נדחפו',
        newEventTitle: '{emoji} <b>{label} חדש!</b>',
        repo: '<b>ריפו:</b>',
        titleLabel: '<b>כותרת:</b>',
        generatedContent: '<b>תוכן שנוצר{threadInfo}:</b>',
        autoGeneratedReview: 'יצרתי תוכן אוטומטי. סקור ואשר?',
        btnApprove: '✅ אשר',
        btnView: '👀 צפה',
        btnEdit: '✏️ ערוך',
        btnEditCompose: '✏️ ערוך',
        btnDelete: '🗑 מחק',

        // Cron — scheduled draft notifications
        scheduledPostFailed: '⚠️ <b>פרסום מתוזמן נכשל</b>',
        draftReturnedToPending: 'הטיוטה הוחזרה לסטטוס ממתין.',
        btnViewDrafts: '📝 צפה בטיוטות',
        btnReconnectInstagram: '🔁 חבר מחדש את אינסטגרם',
        instagramReconnectNeeded: '⚠️ <b>צריך לחבר מחדש את אינסטגרם</b>\n\nטוקן הגישה של אינסטגרם פג ולא ניתן היה לרענן אותו אוטומטית. חבר מחדש כדי להמשיך לפרסם.',
        btnReconnectX: '🔁 חבר מחדש את X',
        xReconnectNeeded: '⚠️ <b>צריך לחבר מחדש את X</b>\n\nהחיבור ל-X פג ולא ניתן היה לרענן אותו אוטומטית. חבר מחדש כדי להמשיך לפרסם ולנתח זהות.',
        btnReconnectLinkedIn: '🔁 חבר מחדש את לינקדאין',
        linkedinReconnectNeeded: '⚠️ <b>צריך לחבר מחדש את לינקדאין</b>\n\nהחיבור ללינקדאין פג ולא ניתן היה לרענן אותו אוטומטית. חבר מחדש כדי להמשיך לפרסם בלינקדאין.',
        scheduledPostPublished: '📤 <b>פוסט מתוזמן פורסם!</b>',
        scheduledPostPartial: '⚠️ <b>פוסט מתוזמן פורסם חלקית</b>',
        publishedAt: '🕐 פורסם ב-{time}',
        publishedTo: '<b>פורסם ב:</b> {summary}',
        publishErrors: '<b>נכשל:</b> {errors}',
        draftReturnedToApproved: 'הטיוטה הוחזרה לסטטוס מאושר. ניתן לנסות שוב.',
        publishJobFailed: '❌ <b>הפרסום נכשל</b>\n\nהפוסט המשיך להיכשל אחרי מספר ניסיונות והופסק.',
        publishStuckRecovered: '⚠️ פרסום של "{title}" לא הושלם (התהליך הופסק). הטיוטה הוחזרה כדי שתוכל לנסות שוב.',
        btnDashboard: '🏠 לוח בקרה',

        // Cron — video notifications
        videoReady: '✅ <b>הסרטון מוכן!</b>',
        videoReadyMsg: 'הסרטון שלך נוצר בהצלחה.',
        btnPublish: '📢 פרסם',
        btnSchedule: '📅 תזמן',
        btnViewDetails: '🎬 צפה בפרטים',
        videoGenerationFailed: '❌ יצירת סרטון נכשלה: {error}',
        btnViewDraft: '🔄 צפה בטיוטה',
        videoGenerationTimedOut: '❌ יצירת סרטון חרגה מזמן אחרי 30 דקות. נסה שוב.',
        scheduledVideoPublished: '📤 <b>סרטון מתוזמן פורסם!</b>',
        scheduledVideoFailed: '⚠️ <b>פרסום סרטון מתוזמן נכשל</b>',
        videoReturnedToCompleted: 'הסרטון הוחזר לסטטוס הושלם.',
        btnViewVideo: '📋 צפה',

        newTweetsDetected: '🔔 <b>ציוצים חדשים זוהו</b>',
        tweetsTotal: 'ציוצים סה"כ',
        generated: '✅ נוצר',
        generateFor: '⚡ צור @{username}',
        openLink: '🔗 פתח',
        btnFast: '⚡ מהיר',
        btnEditRepost: '✏️ ערוך',

        // Commit event notifications
        eventTitle: '{emoji} <b>{label}</b>',
        eventRepo: '<b>ריפו:</b> <code>{repo}</code>',
        eventAuthor: '<b>מחבר:</b> {author}',
        eventStats: '{files} קבצים · +{additions} / -{deletions}',
        eventStatsFilesOnly: '{files} קבצים',
        eventCommitCount: '{count} קומיט(ים)',
        prMergedLabel: 'PR #{number} מוזג',
        pushLabel: '{count} קומיט{plural} נדחפו',
        btnFastCommit: '⚡ מהיר',
        btnEditCommit: '✏️ ערוך',
        btnGenerated: '✅ נוצר',
    },

    actions: {
        accountDeleted: '✅ <b>חשבון נמחק</b>',
        accountDeletedMsg: '@{username} הוסר יחד עם כל הנתונים הקשורים.',
        btnAccounts: '👤 חשבונות',

        analyzingAccount: '🔄 <b>מנתח את @{username}...</b>',
        analyzingAccountDesc: 'מחפש באינטרנט ובונה פרופיל פרסונה. זה עשוי לקחת רגע.',

        repoDeleted: '✅ <b>ריפו נמחק</b>',
        repoDeletedMsg: '<code>{repo}</code> הוסר.',
        webhookRemoved: 'Webhook גם הוסר מ-GitHub.',
        btnRepos: '📦 ריפוז',

        publishedToX: 'פורסם ב-X!\n\n{url}',
        publishedCount: 'פורסמו {count} טיוטות:\n\n{results}',
        publishedDraft: '✅ PR #{number}: {url}',
        publishFailed: '❌ PR #{number}: פרסום נכשל',
        noApprovedDrafts: 'אין טיוטות מאושרות לפרסום.\n\nאשר טיוטות קודם!',
        publishFailedGeneric: 'פרסום נכשל. נסה שוב.',

        scheduleCancelled: 'תזמון בוטל. הטיוטה חזרה לסטטוס ממתין.',

        repostDraftGenerated: '✅ <b>טיוטת ריפוסט נוצרה!</b>',
        repostDraftGeneratedMsg: 'מ-<b>@{username}</b>\n<i>{preview}...</i>\n\nהטיוטה שלך מוכנה וממתינה בטיוטות > ריפוסטים.',
        btnViewDraft: '👁 צפה בטיוטה',

        generationFailed: '❌ <b>היצירה נכשלה</b>',
        generationFailedMsg: 'לא הצלחתי ליצור תוכן. נסה שוב.',
        btnRetry: '🔄 נסה שוב',

        followPrompt: '💡 רוצה לעקוב אחרי <b>@{username}</b> לקבלת התראות ריפוסט אוטומטיות?',
        btnFollow: '👁 עקוב',
        btnNoThanks: '👋 לא תודה',
        nowFollowing: '✅ עוקב אחרי <b>@{username}</b>!\n\nתקבל התראות כשהם מפרסמים ציוצים חדשים.',
        followFailed: '❌ נכשל לעקוב אחרי <b>@{username}</b>. ייתכן שהם כבר בחשבונות שלך.',
        noFollowDismiss: '👋 הבנתי! תמיד אפשר לעקוב אחריהם מאוחר יותר מעמוד החשבונות.',

        generatingImage: '🎨 מייצר תמונה...',

        listDeleteTitle: '🗑 <b>מחק טיוטה?</b>',
        listDeleteWarn: '⚠️ לא ניתן לבטל פעולה זו.',
        btnYesDelete: '✅ כן, מחק',

        invalidDateFormat: '❌ פורמט תאריך לא תקין.',
        scheduleForDate: '📅 <b>תזמון ל-{date}</b>',
        sendTimeHHMM: 'שלח את השעה בפורמט <b>HH:MM</b> (לדוגמה <code>14:30</code>)',
        orFullDateTime: 'או שלח תאריך ושעה מלאים: <code>YYYY-MM-DD HH:MM</code>',

        editDraftTitle: '✏️ <b>ערוך טיוטה</b>',
        editDraftDesc: 'אילו שינויים תרצה לעשות?\n\nשלח את השינויים כטקסט — אעדכן את תוכן הטיוטה.',

        draftNotFoundDeleted: '❌ טיוטה לא נמצאה. ייתכן שנמחקה.',

        characterCreateCancelled: 'יצירת דמות בוטלה.',
        lookCreateCancelled: 'יצירת מראה בוטלה.',
        videoComposeCancelled: 'כתיבת הוראות וידאו בוטלה.',
    },

    schedule: {
        // Schedule day picker
        dayPickerTitle: '📅 <b>תזמון טיוטה</b>',
        selectDay: 'בחר יום ({tz}):',
        orSendFullDateTime: 'או שלח תאריך ושעה מלאים: <code>YYYY-MM-DD HH:MM</code>',
        today: 'היום',
        tomorrow: 'מחר',
        daySun: 'א׳',
        dayMon: 'ב׳',
        dayTue: 'ג׳',
        dayWed: 'ד׳',
        dayThu: 'ה׳',
        dayFri: 'ו׳',
        daySat: 'ש׳',

        contextLost: '❌ הקשר תזמון אבד. נסה שוב מהטיוטה.',
        invalidFormat: '❌ פורמט לא תקין.',
        sendTime: 'שלח שעה: <code>HH:MM</code>',
        orFullDate: 'או תאריך מלא: <code>YYYY-MM-DD HH:MM</code>',
        sendFullDateTime: 'שלח תאריך ושעה מלאים: <code>YYYY-MM-DD HH:MM</code>',
        noDateSelected: '❌ לא נבחר תאריך.',
        invalidTime: '❌ שעה לא תקינה. שעות חייבות להיות 0-23, דקות 0-59.',
        timeExample: 'דוגמה: <code>14:30</code>',
        invalidDateTimeCombination: '❌ שילוב תאריך/שעה לא תקין. נסה שוב.',
        timeInPast: '❌ הזמן הזה עבר.',
        provideFutureTime: 'אנא ספק זמן עתידי.',
        formatHHMM: 'פורמט: <code>HH:MM</code>',
        failedToSchedule: '❌ תזמון טיוטה נכשל. נסה שוב.',
        invalidDatetimeFormat: '❌ פורמט תאריך-שעה לא תקין.',
        useFormat: 'השתמש בפורמט: <code>YYYY-MM-DD HH:MM</code>',
        dateExample: 'דוגמה: <code>2026-02-10 14:00</code>',
        provideFutureDatetime: 'אנא ספק תאריך ושעה עתידיים.',
        formatFull: 'פורמט: <code>YYYY-MM-DD HH:MM</code>',
        provideBothShaAndDatetime: '❌ אנא ספק גם SHA של קומיט וגם תאריך-שעה.',
        shaDatetimeFormat: 'פורמט: <code>SHA YYYY-MM-DD HH:MM</code>',
        shaDatetimeExample: 'דוגמה: <code>abc1234 2024-01-15 14:00</code>',
        scheduledPost: '📅 פוסט מתוזמן ל-{source}\n\nיפורסם ב-{time}',
        scheduleFailed: '❌ <b>תזמון נכשל</b>',
        scheduleFailedMsg: 'לא הצלחתי לעבד <code>{sha}</code>. שלח SHA + תאריך-שעה אחר כדי לנסות שוב.',
    },

    apiKeys: {
        updateGeminiTitle: '🔑 <b>עדכן מפתח API של Gemini</b>',
        updateGeminiDesc: 'שלח את מפתח ה-Gemini API החדש שלך.\n\nקבל אחד בחינם ב:',
        geminiLink: '📖 קבל מפתח',

        updateClaudeTitle: '🔑 <b>עדכן מפתח API של Claude</b>',
        updateClaudeDesc: 'שלח את מפתח ה-Claude API שלך.\n\nקבל אחד ב:',
        claudeConsole: '📖 קבל מפתח',

        updateXTitle: '🔑 <b>עדכן מפתחות X/Twitter</b>',
        updateXDesc: 'שלח את כל 4 הערכים בפורמט המדויק הזה (אחד בכל שורה):',
        xDevPortal: '📖 פורטל מפתחים',

        updateGithubTitle: '🔑 <b>עדכן טוקן GitHub</b>',
        updateGithubDesc: 'שלח את טוקן הגישה האישי החדש שלך ב-GitHub.',
        githubCreateToken: '📖 צור טוקן',

        updateInstagramTitle: '📸 <b>עדכן פרטי Instagram</b>',
        updateInstagramDesc: 'שלח את הפרטים בפורמט הזה (אחד בכל שורה):',
        instagramDevPortal: '📖 Meta developers',
        updateLinkedInTitle: '💼 <b>חבר לינקדאין</b>',
        updateLinkedInDesc: 'לינקדאין מתחבר בצורה מאובטחת דרך OAuth. פתח את האפליקציה כדי לחבר או לחבר מחדש את חשבון הלינקדאין שלך.',
        linkedinConnectApp: '💼 חבר באפליקציה',
    },

    addAccount: {
        invalidUsername: '❌ <b>שם משתמש לא תקין</b>',
        invalidUsernameMsg: '"{username}" לא נראה כשם משתמש תקין של Twitter/X.\n\nשמות משתמש חייבים להיות 1-15 תווים, אלפאנומריים או קו תחתון בלבד.\n\nנסה שוב:',
        alreadyFollowing: '❌ <b>כבר עוקב</b>',
        alreadyFollowingMsg: 'אתה כבר עוקב אחרי @{username}.',
        failedToAddAccount: '❌ הוספת חשבון נכשלה. נסה שוב.',
    },

    settingsKeys: {
        geminiValidationFailed: '❌ אימות מפתח Gemini נכשל (סטטוס {status}). אנא בדוק ונסה שוב.',
        geminiValidationError: '❌ לא הצלחתי לאמת מפתח Gemini. נסה שוב.',
        claudeValidationFailed: '❌ אימות מפתח Claude נכשל. אנא בדוק את המפתח ונסה שוב.',
        claudeValidationError: '❌ לא הצלחתי לאמת מפתח Claude. נסה שוב.',
        retryHint: 'שלח את המפתח שוב לנסות שנית, או לחץ חזרה לביטול.',
        xConnectViaApp: '🔗 <b>החיבור ל-X עבר לאפליקציית הוויב</b> — פתח אותה ולחץ <b>התחבר ל-X</b> להתחברות מאובטחת. (שיטת מפתחות ה-API הישנה הוסרה.)',
        openAppConnectX: '🔗 פתח אפליקציה והתחבר ל-X',
        xExpectedLines: '❌ צפויות 4 שורות (API_KEY, API_SECRET, ACCESS_TOKEN, ACCESS_SECRET), התקבלו {count}.',
        xValidationFailed: '❌ אימות פרטי X נכשל: {error}',
        githubValidationFailed: '❌ אימות טוקן GitHub נכשל (סטטוס {status}). אנא בדוק ונסה שוב.',
        githubValidationError: '❌ לא הצלחתי לאמת טוקן GitHub. נסה שוב.',
        instagramExpectedLines: '❌ צפויות 2 שורות (ACCESS_TOKEN, BUSINESS_ACCOUNT_ID), התקבלו {count}.',
        instagramValidationFailed: '❌ אימות טוקן Instagram נכשל (סטטוס {status}). אנא בדוק ונסה שוב.',
        instagramValidationError: '❌ לא הצלחתי לאמת טוקן Instagram. נסה שוב.',
    },

    editDraft: {
        noDraftSelected: 'לא נבחרה טיוטה לעריכה.',
        editing: '✏️ <b>עורך טיוטה...</b>',
        applying: 'מחיל: "<i>{instruction}</i>"',
        updated: '✅ <b>טיוטה עודכנה!</b>',
        applied: 'הוחל: "<i>{instruction}</i>"',
        btnViewDraft: '👀 צפה בטיוטה',
        editFailed: '❌ <b>עריכה נכשלה</b>',
        editFailedMsg: 'לא הצלחתי להחיל את השינוי. שלח הוראה אחרת כדי לנסות שוב.',
    },

    overview: {
        invalidFormat: '❌ פורמט לא תקין.',
        usage: 'שימוש: <code>/overview owner/repo</code>',
        notWatched: '❌ ריפו <code>{repo}</code> לא נמצא ברשימת המעקב שלך.',
        addFirst: 'הוסף אותו קודם עם /watch.',
        repoNotFound: '❌ ריפו לא נמצא.',
        specifyRepo: '❌ אנא ציין ריפו.',
        bootstrapping: '🔍 יוצר סקירה עבור <code>{repo}</code>...',
        fetchingReadme: 'מביא README ו-PRים אחרונים...',
        bootstrapped: '✅ <b>סקירה נוצרה!</b>',
        summary: '📋 <b>תקציר:</b>',
        techStack: '🛠 <b>מחסנית טכנולוגית:</b>',
        keyFeatures: '⭐ <b>תכונות מרכזיות:</b>',
        targetAudience: '👥 <b>קהל יעד:</b>',
        brandVoice: '🎤 <b>קול מותג:</b>',
        visualTheme: '🎨 <b>ערכת נושא חזותית:</b>',
        contextUsed: 'הקשר זה ישמש כעת ביצירת תוכן לריפו זה.',
        bootstrapFailed: '❌ יצירת סקירה נכשלה עבור <code>{repo}</code>.',
        tryAgain: 'נסה שוב.',
    },

    addRepo: {
        invalidFormat: '❌ <b>פורמט לא תקין</b>',
        invalidFormatMsg: 'השתמש בפורמט: <code>owner/repo</code>',
        btnTryAgain: '🔄 נסה שוב',
        alreadyWatching: '⚠️ <b>כבר במעקב</b>',
        alreadyWatchingMsg: '<code>{repo}</code> כבר ברשימה שלך!',
        repoNotFoundTitle: '❌ <b>ריפו לא נמצא</b>',
        repoNotFoundMsg: '<code>{repo}</code> לא קיים או לא נגיש.\n\nוודא ש:\n• הריפו קיים\n• לטוקן GitHub שלך יש גישה אליו',
        workerUrlNotConfigured: '⚠️ WORKER_URL לא מוגדר. Webhook לא נוצר.',
        webhookCreated: '✅ Webhook נוצר בהצלחה!',
        webhookFailed: '⚠️ יצירת Webhook נכשלה. זיהוי אוטומטי עלול לא לעבוד.\nוודא שלטוקן GitHub שלך יש הרשאת admin:repo_hook.',
        repoAdded: '✅ <b>ריפו נוסף!</b>',
        repoAddedMsg: '<code>{repo}</code> נמצא כעת במעקב.',
        bootstrapping: '🔍 יוצר סקירה עבור <code>{repo}</code>...',
        overviewBootstrapped: '✅ סקירה נוצרה עבור <code>{repo}</code>!\n\nהקשר זה ישפר את איכות התוכן שנוצר.',
        btnViewRepo: '📂 צפה בריפו',
        overviewFailed: '⚠️ לא הצלחתי ליצור סקירה אוטומטית עבור <code>{repo}</code>.\n\nניתן ליצור ידנית עם <code>/overview {repo}</code>',
        addFailed: 'הוספת ריפו נכשלה. נסה שוב.',
    },

    repostInput: {
        invalidTweetUrl: '❌ <b>כתובת ציוץ לא תקינה</b>',
        invalidTweetUrlMsg: 'לא הצלחתי לפענח כתובת ציוץ.',
        tweetNotFound: '❌ <b>ציוץ לא נמצא</b>',
        tweetNotFoundMsg: 'לא הצלחתי להביא ציוץ <code>{tweetId}</code> מ-@{username}.\n\nהציוץ עשוי להיות מחוק, מחשבון פרטי, או שהכתובת שגויה.\n\nנסה כתובת אחרת:',
        rateLimited: 'הגעת למגבלת קריאות ה-API של X. המתן מספר דקות ונסה שוב.',
        creditsDepleted: 'קרדיטים של X API נגמרו. טען את חשבון המפתח של X כדי להמשיך.',
    },

    platforms: {
        // שמות פלטפורמות
        x: 'X',
        post: 'פוסט אינסטגרם',
        story: 'סטורי אינסטגרם',
        reel: 'ריל אינסטגרם',
        linkedin: 'לינקדאין',

        // ממשק בחירה
        selectTargets: 'בחר יעדי פרסום',
        currentTargets: 'יעדים נוכחיים',
        targets: 'יעדים',
        btnPlatforms: 'פלטפורמות',
        btnPublish: 'פרסם',
        btnRepost: 'ריפוסט',

        // פלטפורמות ברירת מחדל (הגדרות)
        defaultPlatforms: 'פלטפורמות ברירת מחדל',
        defaultPlatformsDesc: 'טיוטות חדשות ישתמשו בפלטפורמות אלה כברירת מחדל.',

        // בורר ריפוסט
        repostTitle: 'ריפוסט לפלטפורמות נוספות',
        selectRepostTargets: 'בחר פלטפורמות לפרסום:',
        selected: 'נבחרו',

        // שגיאות
        noTargetSelected: 'אנא בחר לפחות פלטפורמה אחת.',
    },

    thumb: {
        composeTitle: '🖼 <b>יצירת תמונה ממוזערת</b>',
        labelTitle: 'כותרת',
        labelColor: 'צבע',
        labelIcons: 'אייקונים',
        labelImage: 'תמונה',
        labelAspect: 'יחס',
        instructions: 'שלח לי את הבחירות שלך:\n1. "כותרת"\n2. "צבע"\n3. "אייקונים"\nצרף את התמונה (תמונה או קובץ)',
        btnPenDown: '✏️ סיום',
        missing: 'חסר',
        generating: '🖼 מייצר תמונה ממוזערת...',
        generationFailed: '❌ יצירת התמונה הממוזערת נכשלה. נסה שוב.',
        imageNotFound: '❌ התמונה לא נמצאה.',
        notFound: '❌ תמונה ממוזערת לא נמצאה.',
        draftsTitle: 'תמונות ממוזערות',
        draftsCategory: '🖼 תמונות ממוזערות',
        noDrafts: 'אין עדיין תמונות ממוזערות.',
        btnFullRes: 'רזולוציה מלאה',
        deleteConfirm: '🗑 למחוק תמונה ממוזערת זו?',
    },
    imgcreate: {
        composeTitle: '🎨 <b>יצירת תמונה</b>',
        labelPrompt: 'פרומפט',
        labelImage: 'תמונה',
        imagesLabel: 'תמונות',
        messagesWord: 'הודעות',
        charsWord: 'תווים',
        moreWord: 'נוספות',
        instructions: 'שלח טקסט ו/או תמונות — כמה הודעות שתרצה.\nלחץ סיום כשתסיים.',
        btnPenDown: '✏️ סיום',
        missing: 'חסר',
        missingPrompt: 'פרומפט נדרש',
        generating: '🎨 מייצר תמונה...',
        generationFailed: '❌ יצירת התמונה נכשלה. נסה שוב.',
        imageNotFound: '❌ התמונה לא נמצאה.',
        notFound: '❌ התמונה לא נמצאה.',
        draftsTitle: 'תמונות',
        draftsCategory: '🎨 תמונות',
        noDrafts: 'אין עדיין תמונות.',
        btnFullRes: 'רזולוציה מלאה',
        deleteConfirm: '🗑 למחוק תמונה זו?',
    },
};
